import React from 'react';
import { useStore } from '../../store/useStore';
import { MessageSquare } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export const GroundedExplanation: React.FC = () => {
  const { optimizationResult } = useStore();

  if (!optimizationResult) {
    return (
      <div className="card">
        <h2>Grounded Explanation</h2>
        <p className="text-gray">No optimization result available. Run an optimization first.</p>
      </div>
    );
  }

  const explanation = optimizationResult.explanation;
  const explanationText = typeof explanation === 'string'
    ? explanation
    : [
        explanation?.summary ? `### Executive Summary\n${explanation.summary}` : '',
        explanation?.rationale ? `### Rationale\n${explanation.rationale}` : '',
        explanation?.constraint_explanation ? `### Constraint Explanation\n${explanation.constraint_explanation}` : '',
        explanation?.recommendation ? `### Recommendation\n${explanation.recommendation}` : ''
      ].filter(Boolean).join('\n\n') || "No explanation was generated.";

  return (
    <div>
      <h2 style={{ marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
        <MessageSquare size={24} />
        Grounded Explanation
      </h2>
      
      <div className="card">
        <div style={{ padding: '1rem', backgroundColor: 'var(--bg-tertiary)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-light)' }}>
          <p className="text-gray text-sm" style={{ marginBottom: '1rem', fontStyle: 'italic' }}>
            This explanation is deterministically grounded in the exact optimization results generated by the AEMIIF engine.
          </p>
          
          <div className="markdown-body" style={{ lineHeight: 1.6 }}>
            <ReactMarkdown>{explanationText}</ReactMarkdown>
          </div>
        </div>
      </div>
    </div>
  );
};
